In [1]:
%time for i in range(1,10000000): i*i

Wall time: 1.44 s


In [2]:
import numpy as np
array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


### numpy takes less memory to store than list

In [7]:
##adding every elements of each list

##lists first
import numpy as np
l1=[1,2,3]
l2=[1,2,3]

result= [(x+y) for x,y in zip(l1,l2)]
print("adding lists elements", result)


a1=np.array([1,2,3])
a2=np.array([1,2,3])
result=a1+a2
print("adding numpy arrays", result)

adding lists elements [2, 4, 6]
adding numpy arrays [2 4 6]


In [8]:
##finding dimensions of nparray
a1=np.array([1,2,3])
a1.ndim

1

In [10]:
a1=np.array([[1,2],[1,2],[3,3]])
a1.ndim

2

In [12]:
##finding the size each element will occupy
a1.itemsize
##integer in numpy occupies 4 bytes

4

In [17]:
##to print the datatype of np array
b=np.array([1,2,3])
print(b.dtype)

a=np.array([1,2,3],dtype=np.float64)
print(a.dtype)
print(a.itemsize)

int32
float64
8


In [19]:
##size of the array
a.size

3

In [20]:
##shape of the array
a.shape

(3,)

In [21]:
#to fill the array with 0
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
l=range(5)
print(l)

a=np.arange(5)
print(a)

range(0, 5)
[0 1 2 3 4]


In [25]:
#with range
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [26]:
#to generate numbers between two numbers and is an array which is linearly spaced
a=np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [32]:
#reshape the array
a=np.array([[1,2],[2,3],[4,5]])
print(a)
print(a.shape)
a.reshape(2,3)


[[1 2]
 [2 3]
 [4 5]]
(3, 2)


array([[1, 2, 2],
       [3, 4, 5]])

In [33]:
#printing minimum and maximimum element in numpy
print("min=",a.min())
print("max=",a.max())

min= 1
max= 5


In [34]:
#summing all elements in np array
print("sum= ",a.sum())

sum=  17


In [38]:
#axis=0 is column, axis=1 os row
print(a, "\n ")
print(a.sum(axis=0),"\n")

print(a.sum(axis=1))

[[1 2]
 [2 3]
 [4 5]] 
 
[ 7 10] 

[3 5 9]


In [39]:
#square root
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798]])

In [40]:
##standard deviatio of all array elements
np.std(a)

1.3437096247164249

In [41]:
##basic operations
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,7]])

print(a+b)
print(a-b)
print(a*b)
print(a%b)


##dot product that is matrix multiplication
print("\n\n")
print(a.dot(b))

[[ 4  6]
 [ 8 11]]
[[-2 -2]
 [-2 -3]]
[[ 3  8]
 [15 28]]
[[1 2]
 [3 4]]



[[13 18]
 [29 40]]


# indexing and slicing in numpy






In [42]:
a=np.array([1,2,3,4,5])
print(a[1:4])

[2 3 4]


In [43]:
print(a[-1])

5


### slicing for 2dimensional array

In [45]:
a=np.array([[1,2,5],[2,3,6],[3,3,7]])

In [46]:
# first row second column
a[1,2]

6

In [48]:
#for 0-2 excluding 2 rows, print the 1st column
a[0:2,1]

array([2, 3])

In [50]:
#fow all rows print the 2nd and 3rd columns
a[0:3,1:3]

array([[2, 5],
       [3, 6],
       [3, 7]])

# iterate through nupmy array

In [51]:
a=np.array([[1,2,5],[2,3,6],[3,3,7]])

In [53]:
for row in a:
    for column in row:
        print(column)
    print("\n")

1
2
5


2
3
6


3
3
7




In [54]:
for row in a:
    print(row)

[1 2 5]
[2 3 6]
[3 3 7]


In [58]:
##make a numpy a single dimensional array
for i in a.flat:
    print(i)

1
2
5
2
3
6
3
3
7


# stacking two np arrays 

In [62]:
a=np.arange(6).reshape(2,3)
print(a,"\n")
b=np.arange(6,12).reshape(2,3)
print(b,"\n")
np.vstack((a,b))

[[0 1 2]
 [3 4 5]] 

[[ 6  7  8]
 [ 9 10 11]] 



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
#horizontal stack
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# horizontal and vertical split of an array

In [64]:
a=np.arange(30).reshape(2,15)
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [66]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

# indexing with boolean arrays

In [68]:
a=np.arange(6).reshape(2,3)
b=a>3
print(b)

[[False False False]
 [False  True  True]]


In [69]:
#returns whichever values in a array which is true

a[b]

array([4, 5])